export default {
  plugins: ["./dist/stylelint-selector-bem-pattern", "./dist/stylelint-vkui", "./dist/stylelint-logical-shorthands"],
  rules: {
    "max-nesting-depth": [0, { ignoreAtRules: ["supports"] }],
    "selector-max-id": 0,
    "selector-max-type": 0,
    "selector-max-universal": 0,
    "selector-pseudo-element-colon-notation": "double",
    "rule-empty-line-before": ["always", { ignore: ["after-comment", "first-nested"] }],
    "comment-empty-line-before": ["always", { ignore: ["stylelint-commands"], except: ["first-nested"] }],
    "declaration-block-single-line-max-declarations": 1,
    "declaration-property-value-disallowed-list": {
      "/^border/": ["none"],
      "/^(@|--).+/": ["/^#/", "/^rgb/"],
    },
    "declaration-block-no-shorthand-property-overrides": true,
    "at-rule-empty-line-before": ["always", { ignore: ["after-comment"], except: ["first-nested", "after-same-name"] }],
    "declaration-no-important": true,
    "no-duplicate-selectors": true,
    "color-named": "never",
    "function-url-scheme-disallowed-list": ["/^data:/"],
    "length-zero-no-unit": [
      true,
      {
        ignore: ["custom-properties"],
      },
    ],
    "property-disallowed-list": [/^\./, "letter-spacing"],
    "selector-pseudo-class-disallowed-list": ["root"],
    "function-linear-gradient-no-nonstandard-direction": true,
    "plugin/selector-bem-pattern": {
      componentName: "^[A-Z][a-zA-Z0-9]+$",
      componentSelectors: "^\\.{componentName}(?:__[a-z][a-zA-Z0-9]*)?(?:--[a-z][a-zA-Z0-9]*)?$",
      implicitComponents: true,
      ignoreCustomProperties: /.*/,
    },
    "plugin/vkui": true,
    "plugin/logical-shorthands": null,
  },
};
