module.exports = {
  plugins: [
    'stylelint-declaration-strict-value',
    './dist/stylelint-selector-bem-pattern',
    './dist/stylelint-vkui',
    './dist/stylelint-logical-shorthands',
  ],
  rules: {
    'max-nesting-depth': [0, { ignoreAtRules: ['supports'] }],
    'indentation': 2,
    'string-quotes': 'single',
    'selector-max-id': 0,
    'selector-max-type': 0,
    'selector-max-universal': 0,
    'selector-list-comma-newline-after': 'always',
    'selector-pseudo-element-colon-notation': 'double',
    'rule-empty-line-before': [
      'always',
      { ignore: ['after-comment', 'first-nested'] },
    ],
    'comment-empty-line-before': [
      'always',
      { ignore: ['stylelint-commands'], except: ['first-nested'] },
    ],
    'block-opening-brace-space-before': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-block-single-line-max-declarations': 1,
    'declaration-property-value-disallowed-list': {
      '/^border/': ['none'],
      '/^(@|--).+/': ['/^#/', '/^rgb/'],
    },
    'declaration-block-no-shorthand-property-overrides': true,
    'at-rule-empty-line-before': [
      'always',
      { ignore: ['after-comment'], except: ['first-nested', 'after-same-name'] },
    ],
    'max-empty-lines': 1,
    'declaration-no-important': true,
    'no-duplicate-selectors': true,
    'color-named': 'never',
    'function-url-scheme-disallowed-list': ['/^data:/'],
    'length-zero-no-unit': [true, {
      ignore: ['custom-properties'],
    }],
    'property-disallowed-list': [/^\./, 'letter-spacing'],
    'selector-pseudo-class-disallowed-list': ['root'],
    'declaration-block-semicolon-newline-after': 'always',
    'no-extra-semicolons': true,
    'declaration-block-trailing-semicolon': 'always',
    'block-opening-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always',
    'function-linear-gradient-no-nonstandard-direction': true,
    'plugin/selector-bem-pattern': {
      'componentName': '^[A-Z][a-zA-Z0-9]+$',
      'componentSelectors': '^\\.{componentName}(?:__[a-z][a-zA-Z0-9]*)?(?:--[a-z][a-zA-Z0-9]*)?$',
      'implicitComponents': true,
      'ignoreCustomProperties': /.*/,
    },
    'plugin/vkui': true,
    'plugin/logical-shorthands': null,
  },
};
