name: "Pull Request"

on: ["pull_request"]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test
